spine:
- hostname: spine01
  features:
    - pim
    - bgp
    - ospf
    - nv overlay
  loopback0: 192.168.0.1/32
  loopback1: 1.2.3.4/32
  Ethernet1: Ethernet1/1
  description1: to_leaf01_inte1/1
  Ethernet2: Ethernet1/2
  description2: to leaf02_inte1/1
  Ethernet3: Ethernet1/3
  description3: to leaf03_inte3/1
  ospf_process: 100
  pim_rp_address: 1.2.3.4
  pim_grp_list: 224.0.0.0/4
  pim_ssm_range: 232.0.0.0/8
  spine_rp_address:
    - 192.168.0.1
    - 192.168.0.2
  local_bgp_as: 64520
  remote_bgp_as: 64520
  bgp_neighbor:
    - 192.168.0.3
    - 192.168.0.4
    - 192.168.0.5

