---
# tasks file for leaf



#-   name: generate config file
#    template: src=leaf.j2 dest=./CONFIGS/{{item.hostname}}.txt
#    with_items: "{{ leaf }}"

    



-  name: Load leaf configuration from main.yml
   include_vars:
     file: ./vars/main.yml
     name: main_config

-  name: Generate config file
   template:
     src: leaf.j2
     dest: "./CONFIGS/{{ item.hostname }}.txt"
   loop: "{{ main_config.leaf }}"




  
