leaf:
- hostname: leaf01
  features:
    - pim
    - bgp
    - ospf
    - nv overlay
    - fabric forwarding
    - interface-vlan
    - vn-segment-vlan-based
    - telemetry
  loopback0: 192.168.0.3/32
  Vlan1: 10
  vn segment1: 100010
  Vlan2: 999
  vn segment2: 100999
  Ethernet1: Ethernet1/1
  description1: to_spine1_inte1/1
  Ethernet2: Ethernet1/2
  description2: to spine2_inte1/2
  vrf: TENANT1
  vlan:
    - 1
    - 10
    - 999
  l3vni: 100999
  l3vni_svi: 999
  gw_vlan1: 10
  vlan_anycast_gateway1: 10.10.1.254/24
  anycast_gateway_mac: 0000.0011.1234
  ospf_process: 100
  nve_multicast_grp: 224.1.1.192
  pim_rp_address: 1.2.3.4
  pim_grp_list: 224.0.0.0/4
  pim_ssm_range: 232.0.0.0/8
  local_bgp_as: 64520
  remote_bgp_as: 64520
  bgp_neighbor:
    - 192.168.0.1
    - 192.168.0.2
  advertised_network:
    - 10.10.1.0/24

- hostname: leaf02
  features:
    - pim
    - bgp
    - ospf
    - nv overlay
    - fabric forwarding
    - interface-vlan
    - vn-segment-vlan-based
    - telemetry
  loopback0: 192.168.0.4/32
  Vlan1: 20
  vn segment1: 100020
  Vlan2: 999
  vn segment2: 100999
  Ethernet1: Ethernet1/2
  description1: to_spine1_inte1/2
  Ethernet2: Ethernet1/1
  description2: to spine2_inte1/1
  vrf: TENANT1
  vlan:
    - 1
    - 20
    - 999
  l3vni: 100999
  l3vni_svi: 999
  gw_vlan1: 20
  vlan_anycast_gateway1: 10.20.1.254/24
  anycast_gateway_mac: 0000.0011.1234
  ospf_process: 100
  nve_multicast_grp: 224.1.1.192
  pim_rp_address: 1.2.3.4
  pim_grp_list: 224.0.0.0/4
  pim_ssm_range: 232.0.0.0/8
  local_bgp_as: 64520
  remote_bgp_as: 64520
  bgp_neighbor:
    - 192.168.0.1
    - 192.168.0.2
  advertised_network:
    - 10.20.1.0/24

